# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

innerProduct <- function(x, y) {
    .Call(`_sparseLMM_innerProduct`, x, y)
}

parallelInnerProduct <- function(x, y) {
    .Call(`_sparseLMM_parallelInnerProduct`, x, y)
}

closeGenoFile_plink <- function() {
    invisible(.Call(`_sparseLMM_closeGenoFile_plink`))
}

gettotalMarker <- function() {
    .Call(`_sparseLMM_gettotalMarker`)
}

getAlleleFreqVec <- function() {
    .Call(`_sparseLMM_getAlleleFreqVec`)
}

parallelCrossProd <- function(bVec) {
    .Call(`_sparseLMM_parallelCrossProd`, bVec)
}

parallelCrossProd_LOCO <- function(bVec) {
    .Call(`_sparseLMM_parallelCrossProd_LOCO`, bVec)
}

getCrossprodMatAndKin <- function(bVec) {
    .Call(`_sparseLMM_getCrossprodMatAndKin`, bVec)
}

getCrossprodMatAndKin_LOCO <- function(bVec) {
    .Call(`_sparseLMM_getCrossprodMatAndKin_LOCO`, bVec)
}

setgeno <- function(genofile, subSampleInGeno, memoryChunk) {
    invisible(.Call(`_sparseLMM_setgeno`, genofile, subSampleInGeno, memoryChunk))
}

Get_OneSNP_Geno <- function(SNPIdx) {
    .Call(`_sparseLMM_Get_OneSNP_Geno`, SNPIdx)
}

Get_OneSNP_Geno_forVarianceRatio <- function(SNPIdx) {
    .Call(`_sparseLMM_Get_OneSNP_Geno_forVarianceRatio`, SNPIdx)
}

Get_OneSNP_StdGeno <- function(SNPIdx) {
    .Call(`_sparseLMM_Get_OneSNP_StdGeno`, SNPIdx)
}

getDiagOfSigma <- function(wVec, tauVec) {
    .Call(`_sparseLMM_getDiagOfSigma`, wVec, tauVec)
}

getDiagOfSigma_sparse <- function(wVec, tauVec, phi) {
    .Call(`_sparseLMM_getDiagOfSigma_sparse`, wVec, tauVec, phi)
}

getDiagOfSigma_LOCO <- function(wVec, tauVec) {
    .Call(`_sparseLMM_getDiagOfSigma_LOCO`, wVec, tauVec)
}

getCrossprod <- function(bVec, wVec, tauVec) {
    .Call(`_sparseLMM_getCrossprod`, bVec, wVec, tauVec)
}

getCrossprod_sparse <- function(bVec, wVec, tauVec, phi) {
    .Call(`_sparseLMM_getCrossprod_sparse`, bVec, wVec, tauVec, phi)
}

getCrossprod_LOCO <- function(bVec, wVec, tauVec) {
    .Call(`_sparseLMM_getCrossprod_LOCO`, bVec, wVec, tauVec)
}

getPCG1ofSigmaAndVector <- function(wVec, tauVec, bVec, maxiterPCG, tolPCG) {
    .Call(`_sparseLMM_getPCG1ofSigmaAndVector`, wVec, tauVec, bVec, maxiterPCG, tolPCG)
}

getPCG1ofSigmaAndVector_LOCO <- function(wVec, tauVec, bVec, maxiterPCG, tolPCG) {
    .Call(`_sparseLMM_getPCG1ofSigmaAndVector_LOCO`, wVec, tauVec, bVec, maxiterPCG, tolPCG)
}

set_seed <- function(seed) {
    invisible(.Call(`_sparseLMM_set_seed`, seed))
}

nb <- function(n) {
    .Call(`_sparseLMM_nb`, n)
}

setStartEndIndex <- function(startIndex, endIndex) {
    invisible(.Call(`_sparseLMM_setStartEndIndex`, startIndex, endIndex))
}

calCV <- function(xVec) {
    .Call(`_sparseLMM_calCV`, xVec)
}

GetTrace <- function(Sigma_iX, Xmat, wVec, tauVec, cov1, nrun, maxiterPCG, tolPCG, traceCVcutoff) {
    .Call(`_sparseLMM_GetTrace`, Sigma_iX, Xmat, wVec, tauVec, cov1, nrun, maxiterPCG, tolPCG, traceCVcutoff)
}

getCoefficients <- function(Yvec, Xmat, wVec, tauVec, maxiterPCG, tolPCG) {
    .Call(`_sparseLMM_getCoefficients`, Yvec, Xmat, wVec, tauVec, maxiterPCG, tolPCG)
}

getCoefficients_LOCO <- function(Yvec, Xmat, wVec, tauVec, maxiterPCG, tolPCG) {
    .Call(`_sparseLMM_getCoefficients_LOCO`, Yvec, Xmat, wVec, tauVec, maxiterPCG, tolPCG)
}

getCoefficients_q_LOCO <- function(Yvec, Xmat, wVec, tauVec, maxiterPCG, tolPCG) {
    .Call(`_sparseLMM_getCoefficients_q_LOCO`, Yvec, Xmat, wVec, tauVec, maxiterPCG, tolPCG)
}

getAIScore <- function(Yvec, Xmat, wVec, tauVec, Sigma_iY, Sigma_iX, cov, nrun, maxiterPCG, tolPCG, traceCVcutoff) {
    .Call(`_sparseLMM_getAIScore`, Yvec, Xmat, wVec, tauVec, Sigma_iY, Sigma_iX, cov, nrun, maxiterPCG, tolPCG, traceCVcutoff)
}

fitglmmaiRPCG <- function(Yvec, Xmat, wVec, tauVec, Sigma_iY, Sigma_iX, cov, nrun, maxiterPCG, tolPCG, tol, traceCVcutoff) {
    .Call(`_sparseLMM_fitglmmaiRPCG`, Yvec, Xmat, wVec, tauVec, Sigma_iY, Sigma_iX, cov, nrun, maxiterPCG, tolPCG, tol, traceCVcutoff)
}

getSigma_X <- function(wVec, tauVec, Xmat, maxiterPCG, tolPCG) {
    .Call(`_sparseLMM_getSigma_X`, wVec, tauVec, Xmat, maxiterPCG, tolPCG)
}

getSigma_X_sparse <- function(wVec, tauVec, Xmat, maxiterPCG, tolPCG, phi, M, nThreads = 1L) {
    .Call(`_sparseLMM_getSigma_X_sparse`, wVec, tauVec, Xmat, maxiterPCG, tolPCG, phi, M, nThreads)
}

getSigma_X_LOCO <- function(wVec, tauVec, Xmat, maxiterPCG, tolPCG) {
    .Call(`_sparseLMM_getSigma_X_LOCO`, wVec, tauVec, Xmat, maxiterPCG, tolPCG)
}

getSigma_G <- function(wVec, tauVec, Gvec, maxiterPCG, tolPCG) {
    .Call(`_sparseLMM_getSigma_G`, wVec, tauVec, Gvec, maxiterPCG, tolPCG)
}

getSigma_G_sparse <- function(wVec, tauVec, Gvec, maxiterPCG, tolPCG, phi, M, nThreads = 1L) {
    .Call(`_sparseLMM_getSigma_G_sparse`, wVec, tauVec, Gvec, maxiterPCG, tolPCG, phi, M, nThreads)
}

getSigma_G_LOCO <- function(wVec, tauVec, Gvec, maxiterPCG, tolPCG) {
    .Call(`_sparseLMM_getSigma_G_LOCO`, wVec, tauVec, Gvec, maxiterPCG, tolPCG)
}

GetTrace_q <- function(Sigma_iX, Xmat, wVec, tauVec, cov1, nrun, maxiterPCG, tolPCG, traceCVcutoff) {
    .Call(`_sparseLMM_GetTrace_q`, Sigma_iX, Xmat, wVec, tauVec, cov1, nrun, maxiterPCG, tolPCG, traceCVcutoff)
}

getAIScore_q <- function(Yvec, Xmat, wVec, tauVec, nrun, maxiterPCG, tolPCG, traceCVcutoff) {
    .Call(`_sparseLMM_getAIScore_q`, Yvec, Xmat, wVec, tauVec, nrun, maxiterPCG, tolPCG, traceCVcutoff)
}

getAIScore_q_LOCO <- function(Yvec, Xmat, wVec, tauVec, nrun, maxiterPCG, tolPCG, traceCVcutoff) {
    .Call(`_sparseLMM_getAIScore_q_LOCO`, Yvec, Xmat, wVec, tauVec, nrun, maxiterPCG, tolPCG, traceCVcutoff)
}

fitglmmaiRPCG_q_LOCO <- function(Yvec, Xmat, wVec, tauVec, nrun, maxiterPCG, tolPCG, tol, traceCVcutoff) {
    .Call(`_sparseLMM_fitglmmaiRPCG_q_LOCO`, Yvec, Xmat, wVec, tauVec, nrun, maxiterPCG, tolPCG, tol, traceCVcutoff)
}

fitglmmaiRPCG_q <- function(Yvec, Xmat, wVec, tauVec, nrun, maxiterPCG, tolPCG, tol, traceCVcutoff) {
    .Call(`_sparseLMM_fitglmmaiRPCG_q`, Yvec, Xmat, wVec, tauVec, nrun, maxiterPCG, tolPCG, tol, traceCVcutoff)
}

